### ISSUE TITLE
Support AWS managed API

### ISSUE THREAD

**Issue by squadgazzz** [grafana-toolbox/grafana-wtf#141]
Seems like [AWS-managed Grafana API](https://docs.aws.amazon.com/grafana/latest/userguide/Using-Grafana-APIs.html) doesn't support the whole Grafana API(at least `/api/health`)

**Comment by amotl** [comment]
Dear @squadgazzz,

thanks for the report. Does that mean it causes any errors when using grafana-wtf on AMG?

With kind regards,
Andreas.

/cc @bhks

**Comment by squadgazzz** [comment]
> thanks for the report. Does that mean it causes any errors when using grafana-wtf on AMG?

@amotl, yes. `grafana-wtf` tries to call `/api/health` endpoint, which doesn't exist in AWS managed Grafana API. I didn't not investigate it further in terms what can fail next since the app fails on the `health` step.

**Comment by bhks** [comment]
Hi squadgazzz,

Are you using any network restriction on your workspace from AWS Managed grafana ?

**Comment by bhks** [comment]
/healthz is allowed but not the /api/health one.

**Comment by amotl** [comment]
Hi. Thanks for your valuable responses. Currently, I think inquiring the /api/health endpoint is (mostly?) to get hold of the Grafana version on the server side.

https://github.com/grafana-toolbox/grafana-wtf/blob/a5db83eb5bdac2801994cf652a6a739a903bb19e/grafana_wtf/core.py#L323-L345

So, to improve the situation for AMG users, may I ask you for a bit more of your support? That would be so sweet!

a) Will version inquiry also work on the /healthz endpoint?
b) Can you share any documentation or other resources about the /healthz endpoint? I haven't been able to discover anything valuable on a very quick web search.

If version inquiry is not possible with AMG (is it?), do you suggest any other workarounds? Our idea would be to always assume most recent Grafana in this case, but let the user override it manually, when it can not be inquired automatically.

**Comment by squadgazzz** [comment]
> a) Will version inquiry also work on the /healthz endpoint?

This endpoint returns a simple 200OK.

There is the `/api/frontend/settings` endpoint, which returns a lot of the data, including all the versions, etc.
Looks like AWS's version is the same as the Grafana API states: https://grafana.com/docs/grafana/latest/developers/http_api/other/#get-settings

**Comment by bhks** [comment]
Yes that `/api/frontend/settings` API is the right place and also the AWS API for Grafana.

**Comment by amotl** [comment]
Thank you both for your excellent support. @squadgazzz's patch has been merged, and the improvement is included in version 0.20.0, now on PyPI.

-- https://github.com/grafana-toolbox/grafana-wtf/releases/tag/0.20.0
